spring.application.name=tpp-client-app
server.port=8085
management.endpoints.web.exposure.include=health,info
tpp.gateway.base-url=${TPP_GATEWAY_BASE_URL:https://localhost:8443}
tpp.gateway.status-path=${TPP_GATEWAY_STATUS_PATH:/psd2/status}
tpp.gateway.key-store-path=${TPP_KEY_STORE_PATH:../deploy/certs/generated/tpp-client.p12}
tpp.gateway.key-store-password=${TPP_KEY_STORE_PASSWORD:changeit}
tpp.gateway.trust-store-path=${TPP_TRUST_STORE_PATH:../deploy/certs/generated/tpp-truststore.p12}
tpp.gateway.trust-store-password=${TPP_TRUST_STORE_PASSWORD:changeit}
