[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    storage.path /fluent-bit/state

[INPUT]
    Name              tail
    Path              /var/log/psd2-gateway-app/application.log
    Tag               psd2.app
    Read_From_Head    true
    Refresh_Interval  2
    DB                /fluent-bit/state/psd2-app.db

[INPUT]
    Name              tail
    Path              /var/log/adapter-dnb/application.log
    Tag               adapter.dnb
    Read_From_Head    true
    Refresh_Interval  2
    DB                /fluent-bit/state/adapter-dnb.db

[INPUT]
    Name              tail
    Path              /var/log/kong/*.log
    Tag               kong.logs
    Read_From_Head    true
    Refresh_Interval  2
    DB                /fluent-bit/state/kong.db

[FILTER]
    Name    record_modifier
    Match   psd2.app
    Record  service psd2-gateway-app
    Record  layer application
    Record  environment local-poc

[FILTER]
    Name    record_modifier
    Match   adapter.dnb
    Record  service adapter-dnb
    Record  layer application
    Record  environment local-poc

[FILTER]
    Name    record_modifier
    Match   kong.logs
    Record  service kong-psd2-gateway
    Record  layer gateway
    Record  environment local-poc

[OUTPUT]
    Name              splunk
    Match             *
    Host              splunk
    Port              8088
    TLS               On
    TLS.Verify        Off
    Splunk_Token      ${SPLUNK_HEC_TOKEN}
    event_index       main
    event_sourcetype  docker:log
