spring.application.name=psd2-gateway-app
server.port=8080
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
logging.file.name=${APP_LOG_FILE:/var/log/psd2-gateway-app/application.log}
internal.adapter.dnb.base-url=${INTERNAL_ADAPTER_DNB_BASE_URL:https://adapter-dnb:9443}
internal.adapter.dnb.account-summary-path=${INTERNAL_ADAPTER_DNB_ACCOUNT_SUMMARY_PATH:/internal/dnb/accounts/summary}
internal.adapter.dnb.consents-path=${INTERNAL_ADAPTER_DNB_CONSENTS_PATH:/internal/dnb/consents}
internal.adapter.dnb.accounts-path=${INTERNAL_ADAPTER_DNB_ACCOUNTS_PATH:/internal/dnb/accounts}
internal.adapter.dnb.key-store-path=${INTERNAL_ADAPTER_DNB_KEY_STORE_PATH:/certs/gateway-client.p12}
internal.adapter.dnb.key-store-password=${INTERNAL_ADAPTER_DNB_KEY_STORE_PASSWORD:changeit}
internal.adapter.dnb.trust-store-path=${INTERNAL_ADAPTER_DNB_TRUST_STORE_PATH:/certs/gateway-truststore.p12}
internal.adapter.dnb.trust-store-password=${INTERNAL_ADAPTER_DNB_TRUST_STORE_PASSWORD:changeit}
