spring.application.name=adapter-dnb
server.port=9443
management.endpoints.web.exposure.include=health,info
logging.file.name=${ADAPTER_LOG_FILE:/var/log/adapter-dnb/application.log}
server.ssl.enabled=true
server.ssl.key-store=${ADAPTER_DNB_KEY_STORE_PATH:/certs/adapter-dnb.p12}
server.ssl.key-store-password=${ADAPTER_DNB_KEY_STORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.trust-store=${ADAPTER_DNB_TRUST_STORE_PATH:/certs/adapter-dnb-truststore.p12}
server.ssl.trust-store-password=${ADAPTER_DNB_TRUST_STORE_PASSWORD:changeit}
server.ssl.trust-store-type=PKCS12
server.ssl.client-auth=need
internal.policy.path=${INTERNAL_ACCESS_POLICY_PATH:/policy/internal-access-policy.yml}
dnb.mockbank.base-url=${MOCK_DNB_BANK_BASE_URL:https://outbound-dnb-apigw:9445}
dnb.mockbank.consents-path=${MOCK_DNB_BANK_CONSENTS_PATH:/v1/consents}
dnb.mockbank.accounts-path=${MOCK_DNB_BANK_ACCOUNTS_PATH:/v1/accounts}
dnb.mockbank.key-store-path=${MOCK_DNB_BANK_KEY_STORE_PATH:/certs/adapter-dnb.p12}
dnb.mockbank.key-store-password=${MOCK_DNB_BANK_KEY_STORE_PASSWORD:changeit}
dnb.mockbank.trust-store-path=${MOCK_DNB_BANK_TRUST_STORE_PATH:/certs/adapter-dnb-truststore.p12}
dnb.mockbank.trust-store-password=${MOCK_DNB_BANK_TRUST_STORE_PASSWORD:changeit}
